name: beam_border
description: >-
  Animated border beam effect for Flutter. A lightweight widget that adds animated border beam effect around any element.
version: 1.0.1
repository: https://github.com/vladoCimb/border_beam

topics:
  - animation
  - ui
  - effects
  - glow
  - border

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
